interface ListBanksType {
  bank: string
  branches: string[]
}
export const ListBanks: ListBanksType[] = [
  {
    bank: "NHNN Việt Nam (State Bank of Vietnam)",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "Agribank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "VietinBank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "Vietcombank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "MB (Military Bank)",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "BIDV",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "Sacombank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "ACB (Asia Commercial Bank)",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "Eximbank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "Techcombank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "DongA Bank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "PVcomBank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "VCB (Vietnam Construction Bank)",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "Maritime Bank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
  {
    bank: "Saigon Bank",
    branches: [
      "Hà Nội",
      "TP. Hồ Chí Minh",
      "Hải Phòng",
      "Đà Nẵng",
      "Huế",
      "Cần Thơ",
      "Quảng Ninh",
      "Lào Cai",
      "Lai Châu",
      "Điện Biên",
      "Lào Cai",
      "Sơn La",
      "Lai Châu",
      "Yên Bái",
      "Thái Nguyên",
      "Lạng Sơn",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Bắc Giang",
      "Hải Dương",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
    ],
  },
]
